version: '3.8'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: YourPassword123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      my_ipv4_network:
        ipv4_address: 45.77.104.213
      my_ipv6_network:
        ipv6_address: 2001:19f0:1000:173b:5400:04ff:feab:f81f

networks:
  my_ipv4_network:
    ipam:
      driver: default
      config:
        - subnet: 45.77.104.213/32

  my_ipv6_network:
    ipam:
      driver: default
      config:
        - subnet: 2001:19f0:1000:173b:5400:04ff:feab:f81f/128

volumes:
  mssql-data:
